# Generated by Django 2.2.3 on 2019-07-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='due',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
